language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  # newest version without https://github.com/squizlabs/PHP_CodeSniffer/pull/1404
  - composer global require squizlabs/php_codesniffer

script:
  - phpenv rehash
  - git ls-files -z "*.php" | xargs -0 -n1 -P4 php -l
  - |
    if [[ $VALIDATE_STANDARD == yes ]]; then
      COMPOSER_BIN=$(composer global config --absolute bin-dir)
      $COMPOSER_BIN/phpcs . --standard=phpcs.xml --warning-severity=0 --extensions=php -p
    fi
  - |
    if [[ $CHECK_TRANSLATION == yes ]]; then
      php cli/check.translation.php -r
    fi

env:
  - CHECK_TRANSLATION=no VALIDATE_STANDARD=yes

matrix:
  fast_finish: true
  include:
    # PHP 5.3 only runs on Ubuntu 12.04 (precise), not 14.04 (trusty)
    - php: "5.3"
      dist: precise
    - php: "7.2"
      env: CHECK_TRANSLATION=yes VALIDATE_STANDARD=no
    - language: node_js
      node_js:
        - "node"
      php:
        # none
      install:
        - npm install jshint
      script:
        - node_modules/jshint/bin/jshint .
  allow_failures:
    - env: CHECK_TRANSLATION=yes VALIDATE_STANDARD=no
    - dist: precise
