language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

install:
  # newest version without https://github.com/squizlabs/PHP_CodeSniffer/pull/1404
  - pear install PHP_CodeSniffer-3.0.0RC4

script:
  - phpenv rehash
  - |
    if [[ $VALIDATE_STANDARD == yes ]]; then
      phpcs . --standard=phpcs.xml --warning-severity=0 --extensions=php -p
    fi
  - |
    if [[ $CHECK_TRANSLATION == yes ]]; then
      php tools/check.translation.php -r
    fi

env:
  - CHECK_TRANSLATION=no VALIDATE_STANDARD=yes

matrix:
  fast_finish: true
  include:
    - php: "5.3"
      dist: precise
    - php: "7.1"
      env: CHECK_TRANSLATION=yes VALIDATE_STANDARD=no
  allow_failures:
    # PHP 5.3 only runs on Ubuntu 12.04 (precise), not 14.04 (trusty)
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: hhvm
    - php: nightly
    - env: CHECK_TRANSLATION=yes VALIDATE_STANDARD=no
