version: '2.3'

services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - '/path/to/pgsql-data:/var/lib/postgresql/data:Z'
    environment:
    - POSTGRES_USER=freshrss
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=freshrss

  freshrss:
    image: freshrss/freshrss:latest
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      - web
      - default
    volumes:
      - '/your/local/directory/data:/var/www/FreshRSS/data:Z'
    labels:
      - "traefik.backend=freshrss"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:rss.example.com"
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"

networks:
  web:
    external: true

